### ISSUE TITLE
multiple output

### ISSUE THREAD

**Issue by MingBit** [np-8/dash-uploader#13] opened 2020-10-19 14:16 UTC
Hey! thanks a lot for this cool dash-uploader. I tried to integrate it with my dash app. It works perfectly well with a single output. Unfortunately, when it comes to multiple output (e.g. multiple children for different pages), it didn't work.

Any comments?! 
Look forward to your reply. :-)

**Comment by np-8** [comment] 2020-10-19 19:06
Hi! Nice to hear you are liking it! Could you tell what is the dash-uploader version you are using, and provide a minimum code example on how the problem can be reproduced?

**Comment by MingBit** [comment] 2020-10-20 18:02
Sure! 

`
def get_upload_component(id):
    return du.Upload(
        id=id,
        max_file_size=1800,  # 1800 Mb
        filetypes=['pk'],
        upload_id=uuid.uuid1(),  # Unique session id
    )

html.Div(
                    [
                        get_upload_component(id='dash-uploader'),
                    ],
                    style={  # wrapper div style
                        'textAlign': 'center',
                        'width': '200px',
                        'padding': '10px',
                        'margin-left': '1rem',
                        'display': 'inline-block',
                        'color': 'white'
                    })
@app.callback([Output('page_1-1', 'children'),
               Output('page_2-2', 'children'),
               Output('page_3-3', 'children')],
              [Input('dash-uploader', 'isCompleted'),
               Input('dash-uploader', 'fileNames'),
               Input('dash-uploader', 'upload_id')])
def get_a_list(is_completed, filenames, upload_id):
    if is_completed and filenames is not None:
        global object
        object = pp.load_Gnetdata_object(UPLOAD_FOLDER_ROOT + '/' + str(upload_id) + '/' + filenames[0])

        new_page_1 = create_page_1()
        new_page_2 = create_page_2()
        new_page_3 = create_page_3()

        return [new_page_1, new_page_2, new_page_3]

`

So it works with individual pages for a single output.. but not with multiple pages.. :(

**Comment by np-8** [comment] 2020-10-20 19:45
Thank you @MingBit . How are `page_1-1` and `create_page_1()` defined? Could you paste or upload full minimal example with code that I could run as such? It would be easier to spot what is wrong if I could just run your script.

**Comment by MingBit** [comment] 2020-10-20 19:55
yesss.. sure! :-)

So I have a sidebar as a menu and page_1 is the one of the sub-pages. And page_1 will be updated based on the **global object** (upload by user). 

**1) Default page_1**

`page_1 = html.Div(id='page_1-1', children=html.H4('please upload object!', style={'color': 'white'}))`

**2) Create new page_1 once global object uploaded**
```

def create_page_1():
    page_1 = html.Div([
        dbc.Row([
            dbc.Col([
                html.H4('Cell distribution'),
                html.Br(),
                dcc.Graph(id='cell_distribution'),
                dbc.Row([
                    dbc.Col([
                        html.P('color encoded by:', style={'color': 'white'}),
                        dcc.Dropdown(options=get_cellinfo_column(), id='color_code', value='Condition')
                    ]),
                    dbc.Col([
                        html.P('shape encoded by:', style={'color': 'white'}),
                        dcc.Dropdown(options=get_cellinfo_column(), id='shape_code')
                    ])
                ])
            ]),
            dbc.Col([
                html.H4('Cell percentage'),
                html.Br(),
                dcc.Graph(id='cell_percentage')
            ])
        ]),
        html.Br(),
        html.H4("Cell annotation table"),
        html.Hr(),
        dash_table.DataTable(id='table',
                             columns=[{'name': i, 'id': i} for i in object.CellAttrs['CellInfo'].columns],
                             data=object.CellAttrs['CellInfo'].to_dict('records'),
                             fixed_rows={'headers': True},
                             style_table={'overflowX': 'scroll',
                                          'overflowY': 'scroll',
                                          'width': '100%',
                                          'height': '50%',
                                          'minWidth': '100%',
                                          'maxHeight': '50ex'},
                             style_cell={'overflow': 'hidden',
                                         'maxWidth': 2,
                                         'textOverflow': 'ellipsis',
                                         'backgroundColor': '#457b9d',
                                         'color': 'white',
                                         'textAlign': 'center'},
                             style_header={'fontWeight': 'bold',
                                           'color': 'black',
                                           'backgroundColor': 'rgb(230,230,230)'},
                             sort_action='native', sort_mode='multi', filter_action='native')
    ])
    return page_1

```
**3) update call back**
```

@app.callback([Output('page_1-1', 'children'),
               Output('page_2-2', 'children'),
               Output('page_3-3', 'children')],
              [Input('dash-uploader', 'isCompleted'),
               Input('dash-uploader', 'fileNames'),
               Input('dash-uploader', 'upload_id')])
def get_a_list(is_completed, filenames, upload_id):
    if is_completed and filenames is not None:
        global object
        object = pp.load_Gnetdata_object(UPLOAD_FOLDER_ROOT + '/' + str(upload_id) + '/' + filenames[0])

        new_page_1 = create_page_1()
        new_page_2 = create_page_2()
        new_page_3 = create_page_3()

        return [new_page_1, new_page_2, new_page_3]
```

**Comment by MingBit** [comment] 2020-10-20 20:14
The full code can be found at [my github](https://github.com/MingBit/PySCNet/blob/master/dash-pyscnet/app.py)

**Comment by np-8** [comment] 2020-10-21 21:49
Thank you for the code. I tried it but did not encounter any problems, probably because I do not have the data your app wants to use (`.pk` file) - I just get "Invalid file type" message. Could you describe more what do you mean by "it didn't work."?

**Comment by MingBit** [comment] 2020-10-22 08:21
Sorry to make this so complicated! The pickle file was successfully uploaded but the code inside didn't run, meaning the page_1, page_2 and page_3 don't update and  still show the default message '**please upload object**' after data uploaded.

it runs perfectly with 
```
@app.callback(Output('page_1-1', 'children'),
               # Output('page_2-2', 'children'),
               # Output('page_3-3', 'children'),
              [Input('dash-uploader', 'isCompleted'),
               Input('dash-uploader', 'fileNames'),
               Input('dash-uploader', 'upload_id')])
def get_a_list(is_completed, filenames, upload_id):
    if is_completed and filenames is not None:
        global object
        object = pp.load_Gnetdata_object(UPLOAD_FOLDER_ROOT + '/' + str(upload_id) + '/' + filenames[0])

        new_page_1 = create_page_1()
        new_page_2 = create_page_2()
        new_page_3 = create_page_3()

        return [new_page_3]
```

**Comment by MingBit** [comment] 2020-10-22 09:51
Hey! I just test again and it works with two outputs. One is page_1 and the other one is html object from your example. 
So I guess there must be some issues with subpage functions.  Uploader is cool! Thank you very much! :+1: 
```
@app.callback([Output('page_1-1', 'children'),
               # Output('page_2-2', 'children'),
               Output('page_3-3', 'children'),
              **Output('callback-output', 'children')],**
              [Input('dash-uploader', 'isCompleted'),
               Input('dash-uploader', 'fileNames'),
               Input('dash-uploader', 'upload_id')])
```

**Comment by np-8** [comment] 2020-10-22 11:59
I'm happy you figured it out! Is it ok to close this issue?

**Comment by MingBit** [comment] 2020-10-22 12:01
Yeah! Sure! :-)

**Closed** 2020-10-22 12:02 UTC
